# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_tpsalib', [dirname(__file__)])
        except ImportError:
            import _tpsalib
            return _tpsalib
        if fp is not None:
            try:
                _mod = imp.load_module('_tpsalib', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _tpsalib = swig_import_helper()
    del swig_import_helper
else:
    import _tpsalib
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _tpsalib.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _tpsalib.SwigPyIterator_value(self)
    def incr(self, n=1): return _tpsalib.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _tpsalib.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _tpsalib.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _tpsalib.SwigPyIterator_equal(self, *args)
    def copy(self): return _tpsalib.SwigPyIterator_copy(self)
    def next(self): return _tpsalib.SwigPyIterator_next(self)
    def __next__(self): return _tpsalib.SwigPyIterator___next__(self)
    def previous(self): return _tpsalib.SwigPyIterator_previous(self)
    def advance(self, *args): return _tpsalib.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _tpsalib.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _tpsalib.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _tpsalib.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _tpsalib.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _tpsalib.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _tpsalib.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _tpsalib.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _tpsalib.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _tpsalib.DoubleVector___nonzero__(self)
    def __bool__(self): return _tpsalib.DoubleVector___bool__(self)
    def __len__(self): return _tpsalib.DoubleVector___len__(self)
    def pop(self): return _tpsalib.DoubleVector_pop(self)
    def __getslice__(self, *args): return _tpsalib.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _tpsalib.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _tpsalib.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _tpsalib.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _tpsalib.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _tpsalib.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _tpsalib.DoubleVector_append(self, *args)
    def empty(self): return _tpsalib.DoubleVector_empty(self)
    def size(self): return _tpsalib.DoubleVector_size(self)
    def clear(self): return _tpsalib.DoubleVector_clear(self)
    def swap(self, *args): return _tpsalib.DoubleVector_swap(self, *args)
    def get_allocator(self): return _tpsalib.DoubleVector_get_allocator(self)
    def begin(self): return _tpsalib.DoubleVector_begin(self)
    def end(self): return _tpsalib.DoubleVector_end(self)
    def rbegin(self): return _tpsalib.DoubleVector_rbegin(self)
    def rend(self): return _tpsalib.DoubleVector_rend(self)
    def pop_back(self): return _tpsalib.DoubleVector_pop_back(self)
    def erase(self, *args): return _tpsalib.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _tpsalib.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _tpsalib.DoubleVector_push_back(self, *args)
    def front(self): return _tpsalib.DoubleVector_front(self)
    def back(self): return _tpsalib.DoubleVector_back(self)
    def assign(self, *args): return _tpsalib.DoubleVector_assign(self, *args)
    def resize(self, *args): return _tpsalib.DoubleVector_resize(self, *args)
    def insert(self, *args): return _tpsalib.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _tpsalib.DoubleVector_reserve(self, *args)
    def capacity(self): return _tpsalib.DoubleVector_capacity(self)
    __swig_destroy__ = _tpsalib.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _tpsalib.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _tpsalib.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _tpsalib.IntVector___nonzero__(self)
    def __bool__(self): return _tpsalib.IntVector___bool__(self)
    def __len__(self): return _tpsalib.IntVector___len__(self)
    def pop(self): return _tpsalib.IntVector_pop(self)
    def __getslice__(self, *args): return _tpsalib.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _tpsalib.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _tpsalib.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _tpsalib.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _tpsalib.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _tpsalib.IntVector___setitem__(self, *args)
    def append(self, *args): return _tpsalib.IntVector_append(self, *args)
    def empty(self): return _tpsalib.IntVector_empty(self)
    def size(self): return _tpsalib.IntVector_size(self)
    def clear(self): return _tpsalib.IntVector_clear(self)
    def swap(self, *args): return _tpsalib.IntVector_swap(self, *args)
    def get_allocator(self): return _tpsalib.IntVector_get_allocator(self)
    def begin(self): return _tpsalib.IntVector_begin(self)
    def end(self): return _tpsalib.IntVector_end(self)
    def rbegin(self): return _tpsalib.IntVector_rbegin(self)
    def rend(self): return _tpsalib.IntVector_rend(self)
    def pop_back(self): return _tpsalib.IntVector_pop_back(self)
    def erase(self, *args): return _tpsalib.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _tpsalib.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _tpsalib.IntVector_push_back(self, *args)
    def front(self): return _tpsalib.IntVector_front(self)
    def back(self): return _tpsalib.IntVector_back(self)
    def assign(self, *args): return _tpsalib.IntVector_assign(self, *args)
    def resize(self, *args): return _tpsalib.IntVector_resize(self, *args)
    def insert(self, *args): return _tpsalib.IntVector_insert(self, *args)
    def reserve(self, *args): return _tpsalib.IntVector_reserve(self, *args)
    def capacity(self): return _tpsalib.IntVector_capacity(self)
    __swig_destroy__ = _tpsalib.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _tpsalib.IntVector_swigregister
IntVector_swigregister(IntVector)

class DCTPS(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DCTPS, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DCTPS, name)
    __swig_setmethods__["Maximum_TPS_Degree"] = _tpsalib.DCTPS_Maximum_TPS_Degree_set
    __swig_getmethods__["Maximum_TPS_Degree"] = _tpsalib.DCTPS_Maximum_TPS_Degree_get
    if _newclass:Maximum_TPS_Degree = _swig_property(_tpsalib.DCTPS_Maximum_TPS_Degree_get, _tpsalib.DCTPS_Maximum_TPS_Degree_set)
    __swig_setmethods__["TPS_Dim"] = _tpsalib.DCTPS_TPS_Dim_set
    __swig_getmethods__["TPS_Dim"] = _tpsalib.DCTPS_TPS_Dim_get
    if _newclass:TPS_Dim = _swig_property(_tpsalib.DCTPS_TPS_Dim_get, _tpsalib.DCTPS_TPS_Dim_set)
    __swig_setmethods__["polymap"] = _tpsalib.DCTPS_polymap_set
    __swig_getmethods__["polymap"] = _tpsalib.DCTPS_polymap_get
    if _newclass:polymap = _swig_property(_tpsalib.DCTPS_polymap_get, _tpsalib.DCTPS_polymap_set)
    __swig_getmethods__["Initialize"] = lambda x: _tpsalib.DCTPS_Initialize
    if _newclass:Initialize = staticmethod(_tpsalib.DCTPS_Initialize)
    def __init__(self, *args): 
        this = _tpsalib.new_DCTPS(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _tpsalib.delete_DCTPS
    __del__ = lambda self : None;
    def assign(self, *args): return _tpsalib.DCTPS_assign(self, *args)
    def findindex(self, *args): return _tpsalib.DCTPS_findindex(self, *args)
    def findpower(self, *args): return _tpsalib.DCTPS_findpower(self, *args)
    def get_dim(self): return _tpsalib.DCTPS_get_dim(self)
    def get_degree(self): return _tpsalib.DCTPS_get_degree(self)
    def get_terms(self): return _tpsalib.DCTPS_get_terms(self)
    def element(self, *args): return _tpsalib.DCTPS_element(self, *args)
    def print_by_order(self, *args): return _tpsalib.DCTPS_print_by_order(self, *args)
    def __iadd__(self, *args): return _tpsalib.DCTPS___iadd__(self, *args)
    def __isub__(self, *args): return _tpsalib.DCTPS___isub__(self, *args)
    def __imul__(self, *args): return _tpsalib.DCTPS___imul__(self, *args)
    def __idiv__(self, *args): return _tpsalib.DCTPS___idiv__(self, *args)
    def add_to(self, *args): return _tpsalib.DCTPS_add_to(self, *args)
    def minus_to(self, *args): return _tpsalib.DCTPS_minus_to(self, *args)
    def time_to(self, *args): return _tpsalib.DCTPS_time_to(self, *args)
    def divide_to(self, *args): return _tpsalib.DCTPS_divide_to(self, *args)
    def evaluate(self, *args): return _tpsalib.DCTPS_evaluate(self, *args)
    def derivative(self, *args): return _tpsalib.DCTPS_derivative(self, *args)
    def cst(self): return _tpsalib.DCTPS_cst(self)
    def __add__(self, *args): return _tpsalib.DCTPS___add__(self, *args)
    def __radd__(self, *args): return _tpsalib.DCTPS___radd__(self, *args)
    def __sub__(self, *args): return _tpsalib.DCTPS___sub__(self, *args)
    def __rsub__(self, *args): return _tpsalib.DCTPS___rsub__(self, *args)
    def __mul__(self, *args): return _tpsalib.DCTPS___mul__(self, *args)
    def __rmul__(self, *args): return _tpsalib.DCTPS___rmul__(self, *args)
    def __div__(self, *args): return _tpsalib.DCTPS___div__(self, *args)
    def __rdiv__(self, *args): return _tpsalib.DCTPS___rdiv__(self, *args)
    def __neg__(self): return _tpsalib.DCTPS___neg__(self)
    def __pos__(self): return _tpsalib.DCTPS___pos__(self)
    def __repr__(self): return _tpsalib.DCTPS___repr__(self)
DCTPS_swigregister = _tpsalib.DCTPS_swigregister
DCTPS_swigregister(DCTPS)
cvar = _tpsalib.cvar
MAX_TPS_ORDERS = cvar.MAX_TPS_ORDERS

def DCTPS_Initialize(*args):
  return _tpsalib.DCTPS_Initialize(*args)
DCTPS_Initialize = _tpsalib.DCTPS_Initialize

class CCTPS(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CCTPS, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CCTPS, name)
    __swig_setmethods__["Maximum_TPS_Degree"] = _tpsalib.CCTPS_Maximum_TPS_Degree_set
    __swig_getmethods__["Maximum_TPS_Degree"] = _tpsalib.CCTPS_Maximum_TPS_Degree_get
    if _newclass:Maximum_TPS_Degree = _swig_property(_tpsalib.CCTPS_Maximum_TPS_Degree_get, _tpsalib.CCTPS_Maximum_TPS_Degree_set)
    __swig_setmethods__["TPS_Dim"] = _tpsalib.CCTPS_TPS_Dim_set
    __swig_getmethods__["TPS_Dim"] = _tpsalib.CCTPS_TPS_Dim_get
    if _newclass:TPS_Dim = _swig_property(_tpsalib.CCTPS_TPS_Dim_get, _tpsalib.CCTPS_TPS_Dim_set)
    __swig_setmethods__["polymap"] = _tpsalib.CCTPS_polymap_set
    __swig_getmethods__["polymap"] = _tpsalib.CCTPS_polymap_get
    if _newclass:polymap = _swig_property(_tpsalib.CCTPS_polymap_get, _tpsalib.CCTPS_polymap_set)
    __swig_getmethods__["Initialize"] = lambda x: _tpsalib.CCTPS_Initialize
    if _newclass:Initialize = staticmethod(_tpsalib.CCTPS_Initialize)
    def __init__(self, *args): 
        this = _tpsalib.new_CCTPS(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _tpsalib.delete_CCTPS
    __del__ = lambda self : None;
    def assign(self, *args): return _tpsalib.CCTPS_assign(self, *args)
    def findindex(self, *args): return _tpsalib.CCTPS_findindex(self, *args)
    def findpower(self, *args): return _tpsalib.CCTPS_findpower(self, *args)
    def get_dim(self): return _tpsalib.CCTPS_get_dim(self)
    def get_degree(self): return _tpsalib.CCTPS_get_degree(self)
    def get_terms(self): return _tpsalib.CCTPS_get_terms(self)
    def element(self, *args): return _tpsalib.CCTPS_element(self, *args)
    def print_by_order(self, *args): return _tpsalib.CCTPS_print_by_order(self, *args)
    def __iadd__(self, *args): return _tpsalib.CCTPS___iadd__(self, *args)
    def __isub__(self, *args): return _tpsalib.CCTPS___isub__(self, *args)
    def __imul__(self, *args): return _tpsalib.CCTPS___imul__(self, *args)
    def __idiv__(self, *args): return _tpsalib.CCTPS___idiv__(self, *args)
    def add_to(self, *args): return _tpsalib.CCTPS_add_to(self, *args)
    def minus_to(self, *args): return _tpsalib.CCTPS_minus_to(self, *args)
    def time_to(self, *args): return _tpsalib.CCTPS_time_to(self, *args)
    def divide_to(self, *args): return _tpsalib.CCTPS_divide_to(self, *args)
    def evaluate(self, *args): return _tpsalib.CCTPS_evaluate(self, *args)
    def derivative(self, *args): return _tpsalib.CCTPS_derivative(self, *args)
    def cst(self): return _tpsalib.CCTPS_cst(self)
    def __add__(self, *args): return _tpsalib.CCTPS___add__(self, *args)
    def __radd__(self, *args): return _tpsalib.CCTPS___radd__(self, *args)
    def __sub__(self, *args): return _tpsalib.CCTPS___sub__(self, *args)
    def __rsub__(self, *args): return _tpsalib.CCTPS___rsub__(self, *args)
    def __mul__(self, *args): return _tpsalib.CCTPS___mul__(self, *args)
    def __rmul__(self, *args): return _tpsalib.CCTPS___rmul__(self, *args)
    def __div__(self, *args): return _tpsalib.CCTPS___div__(self, *args)
    def __rdiv__(self, *args): return _tpsalib.CCTPS___rdiv__(self, *args)
    def __neg__(self): return _tpsalib.CCTPS___neg__(self)
    def __pos__(self): return _tpsalib.CCTPS___pos__(self)
    def __repr__(self): return _tpsalib.CCTPS___repr__(self)
CCTPS_swigregister = _tpsalib.CCTPS_swigregister
CCTPS_swigregister(CCTPS)

def CCTPS_Initialize(*args):
  return _tpsalib.CCTPS_Initialize(*args)
CCTPS_Initialize = _tpsalib.CCTPS_Initialize

def inv(*args):
  return _tpsalib.inv(*args)
inv = _tpsalib.inv

def exp(*args):
  return _tpsalib.exp(*args)
exp = _tpsalib.exp

def log(*args):
  return _tpsalib.log(*args)
log = _tpsalib.log

def sqrt(*args):
  return _tpsalib.sqrt(*args)
sqrt = _tpsalib.sqrt

def pow(*args):
  return _tpsalib.pow(*args)
pow = _tpsalib.pow

def sin(*args):
  return _tpsalib.sin(*args)
sin = _tpsalib.sin

def cos(*args):
  return _tpsalib.cos(*args)
cos = _tpsalib.cos

def tan(*args):
  return _tpsalib.tan(*args)
tan = _tpsalib.tan

def sinh(*args):
  return _tpsalib.sinh(*args)
sinh = _tpsalib.sinh

def cosh(*args):
  return _tpsalib.cosh(*args)
cosh = _tpsalib.cosh

# This file is compatible with both classic and new-style classes.


